INTG-424: Create Mulesoft deploy action
invitation-homes/mulesoft-deploy-action pull request #1
Opened 2021-04-20 10:26 UTC by faisalkhanani-ih

INTG-424: Create Mulesoft deploy action

2021-04-20 15:04 UTC, edwagner requested changes
Overall this looks good, and it's nice that you were able to use the API instead of the CLI.

It'd be helpful to add a README that explains what this does and an example of how to use it.

2021-04-20 15:04 UTC, edwagner commented on action.yml
> +    description: 'Cloudhub application name pattern'
Similarly, I think we could just pass in the application name (the workflow could have a simple map like `{"dev": "ih-ms-exp-dev-api", "qa": "ih-ms-exp-uat-api", "prod": "ih-ms-exp-api"}` that it uses to send that right application name to this action). That helps simplify this action and means that we can depart from that pattern if/when we need to.

2021-04-20 15:04 UTC, edwagner commented on src/index.js
> +    const GITHUB_TOKEN = process.env.github_token;
Is there a reason why this const is capitalized and the others not? I definitely think we should be consistent, and I would suggest keeping it lowercase.

2021-04-20 17:44 UTC, faisalkhanani-ih commented on src/index.js
> +    const GITHUB_TOKEN = process.env.github_token;
I will fix that.

2021-04-20 17:46 UTC, faisalkhanani-ih commented on action.yml
> +    description: 'Cloudhub application name pattern'
- uses: invitation-homes/mulesoft-deploy-action@main
        with:
          cloudhub-app-name-pattern: "ih-salesforce-push-topic-listener-{ENV}-api"

2021-04-20 17:48 UTC, faisalkhanani-ih commented on action.yml
> +    description: 'Comma separated list of cloudhub environments to upload jar file'
calling it multiple times; means making multiple calls to get release and then release_assets then converting them to buffer etc. but if simply pass `cloudhub-envs: "dev,uat"` it will do the above steps once and just upload it two multiple enviroments. Let me know your thoughts.

2021-04-20 21:33 UTC, edwagner commented on action.yml
> +    description: 'Comma separated list of cloudhub environments to upload jar file'
By multiple calls, you mean that we have two copies of this action running, right? Maybe they could even run in parallel. But really the point is to keep the action simple and focused, and let the workflows compose the action as it makes sense for each situation. I don't think we are worried about efficiency here. Simplicity and ease of understanding, yes.

2021-04-20 21:43 UTC, edwagner commented on action.yml
> +    description: 'Cloudhub application name pattern'
I understand the pattern, but I don't love it:
1) It's the pattern for dev & uat, but not prod. Surprise! `-{ENV}` magically disappears then. So it's not really a pattern. That's confusing.
2) What happens when we have a situation where one of our apps doesn't exactly follow the pattern? Then we have to go change the action and possibly also touch every workflow.
3) Why does an action that deploys an artifact have to know about the naming convention of the destination? Let's just tell the action where we want it to load the artifact. It seems reasonable for a repository's workflow to know the names of its destinations, but not the shared action.

My suggestion is that we hardcode the application names in each workflow. We could hardcode it in a map so that you pass in the environment name and it can look up the hardcoded application name. I think that makes it pretty clear to someone looking at the code what is going on.

2021-04-21 17:58 UTC, edwagner reviewed
This looks great Faisal. Why don't you add a LICENSE file whose contents is the [MIT License](https://mit-license.org) and squash the commits.

2021-04-27 12:54 UTC, edwagner requested changes
Just a few suggestions

2021-04-27 12:54 UTC, edwagner commented on README.md
> +# Mulesoft Build Action
```suggestion
# GitHub Action to deploy a Mulesoft application
```

2021-04-27 12:54 UTC, edwagner commented on README.md
> +A GitHub Action downloads the release artifact from the GitHub repository and uploads it on the Mulesoft Cloudhub runtime environment.
```suggestion
A GitHub Action that downloads the specified release artifact from the GitHub repository and uploads it to the Mulesoft Cloudhub runtime environment.
```

2021-04-27 12:54 UTC, edwagner commented on README.md
> +          cloudhub-org-id: "5d528c97-b639-428c-bd03-bf3b247075c9"
Is there a case when we'd need to change this? I think we could just hardcode it in the action.

2021-04-28 07:05 UTC, merged